version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            -   ..:/workspace:cached
        command: sleep infinity
        environment:
            -   NODE_ENV=development
        ports:
            -   '3000:3000'
